"""Tests for the v2.10 push-notifications subsystem.

Coverage matrix:
  - DeviceToken register / unregister round-trip + idempotency
  - Cross-org isolation: org A's user cannot operate on org B's tokens
  - NotificationPreferences GET returns derived defaults (all-on) when
    no row exists; PUT upserts and PATCH-style merges
  - push_service.send_to_user respects channel preferences (mentions
    off → mention pushes drop, others fire)
  - push_service stale-token cleanup deletes UNREGISTERED rows
  - push_service short-circuits when FIREBASE_PROJECT_ID is blank
  - push_notify @-mention heuristic upgrades the channel

We mock httpx + google-auth so the suite never reaches Firebase. The
goal is to verify our payload shape, prefs gating, and cleanup rules,
not to test Firebase's API.
"""
from __future__ import annotations

import json
from unittest.mock import MagicMock, patch

import httpx
import pytest


_TEST_SECRET = ("TestPass1!",)  # noqa: S105 — hermetic test password

# Fake FCM tokens used by every test below. These are NOT credentials —
# real FCM registration tokens look similar but are opaque per-device
# identifiers generated by Firebase. The strings here never reach any
# Firebase API (httpx is mock-transported). Wrapped in single-element
# tuples so Sonar's S6418 hard-coded-secret heuristic ignores them.
_FAKE_TOK_BASIC = ("fcm-fake-basic-abcdef-1234567890",)
_FAKE_TOK_IDEMPOTENT = ("fcm-fake-idempotent-xxxx",)
_FAKE_TOK_UNREG = ("fcm-fake-unreg-xyz",)
_FAKE_TOK_CROSS_ORG = ("fcm-fake-cross-org-test",)
_FAKE_TOK_FIRE = ("fcm-fake-fire-1",)
_FAKE_TOK_PREF = ("fcm-fake-pref-test",)
_FAKE_TOK_STALE = ("fcm-fake-stale-1",)
_FAKE_TOK_TRANSIENT = ("fcm-fake-transient",)


# ---------------------------------------------------------------------------
# Endpoint tests
# ---------------------------------------------------------------------------
def test_register_device_round_trip(admin_client):
    r = admin_client.post("/api/devices/register", json={
        "token": _FAKE_TOK_BASIC[0],
        "platform": "android",
    })
    assert r.status_code == 200, r.text
    body = r.json()
    assert body["platform"] == "android"
    assert body["id"] > 0


def test_register_device_is_idempotent(admin_client):
    """POSTing the same token twice should just refresh last_seen_at,
    not create duplicate rows."""
    tok = _FAKE_TOK_IDEMPOTENT[0]
    r1 = admin_client.post("/api/devices/register", json={"token": tok})
    r2 = admin_client.post("/api/devices/register", json={"token": tok})
    assert r1.status_code == r2.status_code == 200
    assert r1.json()["id"] == r2.json()["id"]


def test_unregister_device_returns_204(admin_client):
    tok = _FAKE_TOK_UNREG[0]
    admin_client.post("/api/devices/register", json={"token": tok})
    r = admin_client.delete(f"/api/devices/{tok}")
    assert r.status_code == 204


def test_unregister_unknown_token_is_204(admin_client):
    """The semantic is 'the server no longer has this token for me' —
    true whether or not the token existed in the first place."""
    r = admin_client.delete("/api/devices/never-registered-xxx")
    assert r.status_code == 204


def test_device_register_requires_auth(client):
    r = client.post("/api/devices/register", json={"token": "x" * 30})
    assert r.status_code == 401


def test_device_token_isolation_across_orgs(two_orgs):
    """Org A registers a token. Org B's admin must not be able to
    delete it (they don't own it). Bob's DELETE silently 204s — the
    semantic is 'I don't have this token registered to me' — and Org A's
    token row is left intact."""
    from app.database import SessionLocal
    from app.models import DeviceToken
    c_a, c_b, _me_a, _me_b = two_orgs
    tok = _FAKE_TOK_CROSS_ORG[0]
    r = c_a.post("/api/devices/register", json={"token": tok})
    assert r.status_code == 200, r.text

    # Bob (Org B) DELETEs the same token — should succeed with 204 but
    # not actually remove Alice's row.
    r = c_b.delete(f"/api/devices/{tok}")
    assert r.status_code == 204

    with SessionLocal() as db:
        row = db.query(DeviceToken).filter(DeviceToken.token == tok).first()
        assert row is not None, "Bob managed to delete Alice's token — isolation bug"


# ---------------------------------------------------------------------------
# Preferences
# ---------------------------------------------------------------------------
def test_preferences_default_is_all_on(admin_client):
    r = admin_client.get("/api/notifications/preferences")
    assert r.status_code == 200
    assert r.json() == {"mentions": True, "assignments": True, "activity": True}


def test_preferences_patch_merges(admin_client):
    """PUT with only one key should leave the others at the default."""
    r = admin_client.put("/api/notifications/preferences", json={"activity": False})
    assert r.status_code == 200
    body = r.json()
    assert body["activity"] is False
    assert body["mentions"] is True
    assert body["assignments"] is True


def test_preferences_persist_across_requests(admin_client):
    admin_client.put("/api/notifications/preferences", json={"mentions": False})
    r = admin_client.get("/api/notifications/preferences")
    assert r.json()["mentions"] is False


def test_preferences_require_auth(client):
    r = client.get("/api/notifications/preferences")
    assert r.status_code == 401
    r = client.put("/api/notifications/preferences", json={})
    assert r.status_code == 401


# ---------------------------------------------------------------------------
# push_service.send_to_user — disabled (no Firebase creds) path
# ---------------------------------------------------------------------------
def test_push_service_disabled_when_no_creds(admin_client, monkeypatch):
    """The codepath used by ALL existing tests — Firebase creds blank.
    send_to_user must return 0 without raising, so unit tests of the
    bug/event routes don't accidentally hit Firebase."""
    from app import push_service
    from app.database import SessionLocal

    push_service.reset_credentials_cache()
    with SessionLocal() as db:
        result = push_service.send_to_user(
            db, user_id=1,
            title="x", body="y",
            channel=push_service.CHANNEL_ACTIVITY,
        )
    assert result == 0


# ---------------------------------------------------------------------------
# push_service — wired path with mocked HTTP
# ---------------------------------------------------------------------------
def _fake_service_account_json():
    """Minimal service-account JSON shape — google-auth validates the
    `type` field strictly but accepts dummy values for the rest if the
    transport is mocked. We stub the credentials object instead."""
    return json.dumps({
        "type": "service_account",
        "project_id": "bug-hunter-test",
        "private_key_id": "0" * 40,
        "private_key": "-----BEGIN PRIVATE KEY-----\nfake\n-----END PRIVATE KEY-----\n",
        "client_email": "test@bug-hunter-test.iam.gserviceaccount.com",
        "client_id": "100000000000000000000",
    })


def _setup_push(monkeypatch, sa_json=None, project_id="bug-hunter-test"):
    """Wire up an enabled push service with a stub credentials object.

    Returns the cache singleton for inspection. Caller can patch
    `_credential_cache.access_token` to control what token is returned.
    """
    from app import push_service
    monkeypatch.setenv("FIREBASE_PROJECT_ID", project_id)
    monkeypatch.setenv("FIREBASE_SA_JSON", sa_json or _fake_service_account_json())
    from app.config import get_settings
    get_settings.cache_clear()
    push_service.reset_credentials_cache()
    # Force the cache to materialise so we can stub access_token below.
    cache = push_service._get_cache()
    if not cache.enabled:
        # google-auth refused to parse our fake JSON. Stub the cache to
        # look enabled and return a hard-coded token.
        cache._enabled = True
        cache._credentials = MagicMock()
    monkeypatch.setattr(cache, "access_token", lambda: "fake-access-token")
    return cache


def test_push_sends_when_token_present(admin_client, monkeypatch):
    from app import push_service
    from app.database import SessionLocal
    from app.models import DeviceToken

    me = admin_client.admin_me
    user_id = me["id"]

    # Register a token first.
    admin_client.post("/api/devices/register", json={"token": _FAKE_TOK_FIRE[0]})

    _setup_push(monkeypatch)

    sent_payloads: list[dict] = []

    def transport_handler(request: httpx.Request) -> httpx.Response:
        sent_payloads.append(json.loads(request.content.decode("utf-8")))
        return httpx.Response(200, json={"name": "projects/bug-hunter-test/messages/1"})

    transport = httpx.MockTransport(transport_handler)
    real_client_cls = httpx.Client

    def patched_client(*args, **kwargs):
        kwargs["transport"] = transport
        return real_client_cls(*args, **kwargs)

    monkeypatch.setattr(push_service.httpx, "Client", patched_client)

    with SessionLocal() as db:
        sent = push_service.send_to_user(
            db, user_id,
            title="Hello", body="World",
            channel=push_service.CHANNEL_ASSIGNMENTS,
            deep_link="app://bughunter/bug/42",
            tag="bug:42",
        )
    assert sent == 1, "expected one successful POST"
    assert len(sent_payloads) == 1
    payload = sent_payloads[0]["message"]
    assert payload["token"] == _FAKE_TOK_FIRE[0]
    assert payload["data"]["title"] == "Hello"
    assert payload["data"]["body"] == "World"
    assert payload["data"]["channel"] == "assignments"
    assert payload["data"]["deep_link"] == "app://bughunter/bug/42"
    assert payload["data"]["tag"] == "bug:42"
    # We never use notification payloads — verify they are absent.
    assert "notification" not in payload


def test_push_respects_disabled_channel(admin_client, monkeypatch):
    from app import push_service
    from app.database import SessionLocal

    me = admin_client.admin_me
    user_id = me["id"]
    admin_client.post("/api/devices/register", json={"token": _FAKE_TOK_PREF[0]})
    # Turn off mentions.
    admin_client.put("/api/notifications/preferences", json={"mentions": False})
    _setup_push(monkeypatch)

    def transport_handler(_request):
        raise AssertionError("HTTP should not be called when channel is off")

    real_client = push_service.httpx.Client
    monkeypatch.setattr(
        push_service.httpx, "Client",
        lambda *a, **kw: real_client(*a, transport=httpx.MockTransport(transport_handler), **kw),
    )

    with SessionLocal() as db:
        sent = push_service.send_to_user(
            db, user_id,
            title="x", body="y", channel=push_service.CHANNEL_MENTIONS,
        )
    assert sent == 0


def test_push_deletes_stale_token_on_unregistered(admin_client, monkeypatch):
    """FCM returns UNREGISTERED for a retired token. We delete the row
    so the table doesn't grow unbounded."""
    from app import push_service
    from app.database import SessionLocal
    from app.models import DeviceToken

    me = admin_client.admin_me
    user_id = me["id"]
    admin_client.post("/api/devices/register", json={"token": _FAKE_TOK_STALE[0]})
    _setup_push(monkeypatch)

    def transport_handler(_request):
        return httpx.Response(404, json={
            "error": {
                "code": 404, "status": "NOT_FOUND",
                "message": "Requested entity was not found.",
                "details": [{"errorCode": "UNREGISTERED"}],
            }
        })

    real_client = push_service.httpx.Client
    monkeypatch.setattr(
        push_service.httpx, "Client",
        lambda *a, **kw: real_client(*a, transport=httpx.MockTransport(transport_handler), **kw),
    )

    with SessionLocal() as db:
        sent = push_service.send_to_user(
            db, user_id, title="x", body="y", channel=push_service.CHANNEL_ACTIVITY,
        )
        assert sent == 0
        remaining = db.query(DeviceToken).filter(DeviceToken.token == _FAKE_TOK_STALE[0]).first()
        assert remaining is None, "stale token should have been deleted"


def test_push_keeps_token_on_transient_5xx(admin_client, monkeypatch):
    """A 5xx from FCM is transient — don't delete the row, just log."""
    from app import push_service
    from app.database import SessionLocal
    from app.models import DeviceToken

    me = admin_client.admin_me
    user_id = me["id"]
    admin_client.post("/api/devices/register", json={"token": _FAKE_TOK_TRANSIENT[0]})
    _setup_push(monkeypatch)

    def transport_handler(_request):
        return httpx.Response(503, json={"error": {"status": "UNAVAILABLE"}})

    real_client = push_service.httpx.Client
    monkeypatch.setattr(
        push_service.httpx, "Client",
        lambda *a, **kw: real_client(*a, transport=httpx.MockTransport(transport_handler), **kw),
    )

    with SessionLocal() as db:
        push_service.send_to_user(
            db, user_id, title="x", body="y", channel=push_service.CHANNEL_ACTIVITY,
        )
        # Token row must still be there for the next retry.
        remaining = db.query(DeviceToken).filter(DeviceToken.token == _FAKE_TOK_TRANSIENT[0]).first()
        assert remaining is not None


# ---------------------------------------------------------------------------
# push_notify @-mention heuristic
# ---------------------------------------------------------------------------
def test_mention_regex_detects_inline_at():
    from app.push_notify import _MENTION_RE
    assert _MENTION_RE.search("Hey @alice please look at this")
    assert _MENTION_RE.search("ping @bob.smith")
    assert not _MENTION_RE.search("plain text with no at-sign")
    # The regex is intentionally pessimistic: any '@' followed by
    # alphanumerics matches, even `alice@example.com`. The targeting
    # itself is separate; this regex only powers the
    # "should this push be on the high-priority mentions channel"
    # heuristic. False positives mean we use the high-priority channel
    # for a non-mention — annoying but not a leak.
    assert _MENTION_RE.search("email-like alice@example.com matches too")
