"""Upgrading existing databases: the earlier enterprise edition (its own schema, generated by
that edition's code and stored as tests/fixtures/legacy_enterprise.sql) and the single-tenant
Bug Hunter schema that has no organizations at all."""
from __future__ import annotations

import sqlite3
import sys
from pathlib import Path

import pytest

FIXTURE = Path(__file__).parent / "fixtures" / "legacy_enterprise.sql"


def _boot(monkeypatch, db_file, **env):
    """Import a fresh copy of the app on ``db_file``; returns the TestClient factory module."""
    monkeypatch.setenv("DATABASE_URL", f"sqlite:///{db_file}")
    monkeypatch.setenv("EMAIL_BACKEND", "disabled")
    monkeypatch.setenv("SESSION_SECRET", "upgrade_test_secret_value")
    monkeypatch.setenv("PASSWORD_BREACH_CHECK_ENABLED", "false")
    monkeypatch.setenv("WEB_PUSH_ENABLED", "false")
    monkeypatch.setenv("AUTO_LOGIN_ENABLED", "false")
    monkeypatch.setenv("BOOTSTRAP_ADMIN_EMAIL", "")
    monkeypatch.setenv("BOOTSTRAP_ADMIN_PASSWORD", "")
    for key, value in env.items():
        monkeypatch.setenv(key, value)
    old = sys.modules.get("app.database")
    if old is not None:
        old.engine.dispose()
    for mod in list(sys.modules):
        if mod == "app" or mod.startswith("app."):
            del sys.modules[mod]
    from app.config import get_settings

    get_settings.cache_clear()  # type: ignore[attr-defined]
    from fastapi.testclient import TestClient

    from app.main import app

    return TestClient, app


def _login(client_cls, app, email, password):
    c = client_cls(app)
    res = c.post("/api/auth/login", json={"email": email, "password": password})
    assert res.status_code == 200, f"{email}: {res.text}"
    return c, res.json()


@pytest.fixture
def legacy_enterprise_db(tmp_path):
    db_file = tmp_path / "legacy_enterprise.db"
    con = sqlite3.connect(db_file)
    con.executescript(FIXTURE.read_text(encoding="utf-8"))
    con.commit()
    con.close()
    return db_file


def test_old_enterprise_database_upgrades_in_place(legacy_enterprise_db, monkeypatch):
    client_cls, app = _boot(monkeypatch, legacy_enterprise_db)
    with client_cls(app):
        admin, me = _login(client_cls, app, "admin@legacy.test", "Legacy-Pass-1")
        assert me["organization_name"] == "Legacy Corp"
        assert me["role"] == "admin"

        lead, lead_me = _login(client_cls, app, "lead@legacy.test", "Legacy-Pass-2")
        member, member_me = _login(client_cls, app, "member@legacy.test", "Legacy-Pass-3")
        # the retired "member" role is the plain user role now
        assert lead_me["role"] == member_me["role"] == "user"

        # memberships keep their project role
        (project,) = lead.get("/api/projects").json()
        assert project["name"] == "Billing"
        assert project["can_manage"] is True
        assert project["key"]
        (member_project,) = member.get("/api/projects").json()
        assert member_project["can_manage"] is False
        roles = {m["user_email"]: m["project_role"] for m in admin.get(f"/api/projects/{project['id']}/members").json()}
        assert roles == {"lead@legacy.test": "lead", "member@legacy.test": "member"}

        # the old item and its assignee are intact and visible to project members
        listing = member.get("/api/bugs").json()
        assert [b["title"] for b in listing["items"]] == ["Legacy bug"]

        # the second organization is unaffected and cannot see the first one's data
        second, second_me = _login(client_cls, app, "admin@second.test", "Second-Pass-1")
        assert second_me["organization_name"] == "Second Corp"
        assert second.get("/api/bugs").json()["total"] == 0
        assert [p["name"] for p in second.get("/api/projects").json()] == ["Billing"]
        assert second_me["org_id"] != me["org_id"]

        # push registrations and per-channel preferences moved across
        assert member.get("/api/notifications/preferences").json() == {
            "mentions": True, "assignments": False, "activity": True}
        assert member.post("/api/devices/register", json={"token": "legacy-fcm-token-0000000001"}).status_code == 200
        assert lead.post("/api/devices/register", json={"token": "legacy-fcm-token-0000000001"}).status_code == 409


def test_second_boot_of_an_upgraded_database_changes_nothing(legacy_enterprise_db, monkeypatch):
    def snapshot():
        con = sqlite3.connect(legacy_enterprise_db)
        try:
            tables = [r[0] for r in con.execute(
                "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")]
            return {t: con.execute(f"SELECT * FROM {t} ORDER BY 1").fetchall() for t in tables
                    if t not in {"sessions", "activity_log"}}
        finally:
            con.close()

    client_cls, app = _boot(monkeypatch, legacy_enterprise_db)
    with client_cls(app):
        pass
    first = snapshot()
    client_cls, app = _boot(monkeypatch, legacy_enterprise_db)
    with client_cls(app):
        pass
    assert snapshot() == first


def test_single_tenant_database_joins_one_organization_and_keeps_every_row(tmp_path, monkeypatch):
    db_file = tmp_path / "single_tenant.db"
    con = sqlite3.connect(db_file)
    con.executescript(
        """
        CREATE TABLE users (
            id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE,
            role TEXT NOT NULL DEFAULT 'user', is_active BOOLEAN NOT NULL DEFAULT 1,
            password_hash TEXT NOT NULL DEFAULT '', created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
        );
        CREATE TABLE projects (
            id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE,
            description TEXT NOT NULL DEFAULT '', color TEXT NOT NULL DEFAULT '#c9764f',
            created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
        );
        CREATE TABLE events (
            id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL,
            created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL
        );
        INSERT INTO projects (name, created_at, updated_at) VALUES ('Alpha', '2026-01-01', '2026-01-01');
        INSERT INTO projects (name, created_at, updated_at) VALUES ('Beta', '2026-01-01', '2026-01-01');
        INSERT INTO projects (name, created_at, updated_at) VALUES ('Alpine', '2026-01-01', '2026-01-01');
        INSERT INTO events (name, created_at, updated_at) VALUES ('Standup', '2026-01-01', '2026-01-01');
        """
    )
    con.commit()
    con.close()

    client_cls, app = _boot(
        monkeypatch, db_file, BOOTSTRAP_ADMIN_EMAIL="admin@test.local", BOOTSTRAP_ADMIN_PASSWORD="Admin1234",
        BOOTSTRAP_ORG_NAME="Acme Legacy")
    with client_cls(app):
        admin, me = _login(client_cls, app, "admin@test.local", "Admin1234")
        assert me["organization_name"] == "Acme Legacy"
        projects = admin.get("/api/projects").json()
        assert {p["name"] for p in projects} >= {"Alpha", "Beta", "Alpine"}
        keys = [p["key"] for p in projects]
        assert len(keys) == len(set(keys))
        assert all(len(k) >= 2 for k in keys)
        assert [e["name"] for e in admin.get("/api/events").json()] == ["Standup"]

    con = sqlite3.connect(db_file)
    try:
        assert con.execute("SELECT count(*) FROM organizations").fetchone()[0] == 1
        assert con.execute("SELECT count(*) FROM projects WHERE org_id IS NULL").fetchone()[0] == 0
        assert con.execute("SELECT count(*) FROM events WHERE org_id IS NULL").fetchone()[0] == 0
    finally:
        con.close()
